datavolume:
#  restart: on-failure:10
  image: ubuntu:trusty
  volumes:
    - /opt/known/mysql:/var/lib/mysql
    - /opt/known/uploads:/known/uploads
    - /opt/known/IdnoPlugins:/var/www/known/IdnoPlugins

mysql:
#  restart: on-failure:10
  image: mysql
  volumes_from:
    - datavolume
  environment:
    - MYSQL_DATABASE=known
    - MYSQL_USER=known
    - MYSQL_PASSWORD=knownpassword
    - MYSQL_ROOT_PASSWORD=rootpassword

known:
#  restart: on-failure:10
  image: davesgonechina/known
  volumes_from:
    - datavolume
  environment:
    - MYSQL_DATABASE=known
    - MYSQL_USER=known
    - MYSQL_PASSWORD=knownpassword
  ports:
    - "80:80"
  links:
    - "mysql:mysql"
